import type {
  AppData,
  Diagnosis,
  IntakeForm,
  KpiStatus,
  Priority,
} from "./types";
import { uid } from "./utils";

export const leadStages = [
  "nuevo lead",
  "formulario 1 enviado",
  "investigacion en progreso",
  "sesion inicial agendada",
  "propuesta enviada",
  "negociacion",
  "cliente ganado",
  "perdido",
] as const;

export const taskStatuses = [
  "pendiente",
  "en proceso",
  "bloqueada",
  "en revision",
  "terminada",
] as const;

export const projectStatuses = [
  "planeado",
  "en progreso",
  "pausado",
  "en revision",
  "completado",
  "cancelado",
] as const;

export const consultingPackages = [
  {
    id: "pkg_express",
    name: "Diagnóstico Express + Recomendaciones",
    duration: "1 semana",
    description:
      "Análisis rápido con entrevistas a líderes, revisión documental básica y detección de principales áreas de mejora. Entrega reporte ejecutivo con mapa de problemas y recomendaciones iniciales.",
  },
  {
    id: "pkg_plan",
    name: "Diagnóstico + Plan de Acción",
    duration: "2-3 semanas",
    description:
      "Evaluación profunda de procesos clave, identificación de causa raíz, definición de KPIs y plan de acción detallado con responsables y tiempos.",
  },
  {
    id: "pkg_implementacion",
    name: "Diagnóstico + Implementación",
    duration: "1-2 meses",
    description:
      "Diagnóstico, plan de acción y ejecución inicial en un área prioritaria con acompañamiento para asegurar resultados inmediatos.",
  },
  {
    id: "pkg_integral",
    name: "Proyecto Integral",
    duration: "6-12 meses",
    description:
      "Implementación completa del modelo L.E.A.D. con diagnóstico, capacitación, acompañamiento en varias áreas, estandarización de procesos y roadmap de mejora continua.",
  },
  {
    id: "pkg_sprint",
    name: "Sprint de Mejora",
    duration: "2-4 semanas",
    description:
      "Intervención enfocada en un problema puntual con solución rápida, ejecución corta y resultados medibles.",
  },
  {
    id: "pkg_mensual",
    name: "Acompañamiento Mensual",
    duration: "Mensual",
    description:
      "Asesoría estratégica recurrente con revisión de KPIs y soporte a líderes en toma de decisiones.",
  },
  {
    id: "pkg_mentoria",
    name: "Mentoría Estratégica + Coaching Ejecutivo",
    duration: "Mínimo 3 meses",
    description:
      "Sesiones 1:1 con directores o gerentes para fortalecer liderazgo, comunicación y dirección estratégica.",
  },
  {
    id: "pkg_licencia",
    name: "Licencia Anual de Acompañamiento",
    duration: "12 meses",
    description:
      "Acceso permanente a consultor estratégico con revisiones mensuales de KPIs, asesoría continua, auditorías trimestrales y plan anual de mejora.",
  },
  {
    id: "pkg_custom",
    name: "Proyecto Personalizado",
    duration: "Variable",
    description:
      "Diseño a medida según los objetivos del cliente. Puede combinar paquetes y soluciones externas bajo coordinación LC.",
  },
] as const;

export const demoData: AppData = {
  organization: {
    id: "org_lc",
    name: "LC Consulting",
  },
  users: [
    {
      id: "usr_admin",
      name: "Laura Cardenas",
      email: "admin@lcconsulting.mx",
      role: "admin",
      organizationId: "org_lc",
    },
    {
      id: "usr_consultant",
      name: "Mateo Ruiz",
      email: "consultor@lcconsulting.mx",
      role: "consultant",
      organizationId: "org_lc",
    },
    {
      id: "usr_viewer",
      name: "Sofia Vega",
      email: "viewer@lcconsulting.mx",
      role: "viewer",
      organizationId: "org_lc",
    },
  ],
  leads: [
    {
      id: "lead_azul",
      company: "Optica Azul",
      contactName: "Daniela Mora",
      email: "daniela@opticaazul.mx",
      phone: "+52 656 101 2244",
      stage: "sesion inicial agendada",
      estimatedValue: 78000,
      closeProbability: 64,
      nextStep: "Diagnostico operativo el jueves",
      source: "Referido",
      lastInteraction: "2026-06-29",
      recommendedPackage: "Diagnóstico + Plan de Acción",
      intake: {
        yearsOperating: 4,
        howFoundUs: "Referido",
        mainProblem: "Ventas sin seguimiento, inventario desordenado y baja recompra.",
        expectedResult: "Ordenar el seguimiento comercial y aumentar ventas en 3 meses.",
        previousConsulting: "no",
        budgetAvailable: "definido",
        willingToParticipate: "sí",
        internalFlag: "verde",
      },
    },
    {
      id: "lead_alfa",
      company: "Transporte Alfa",
      contactName: "Hector Salas",
      email: "hector@alfa-log.mx",
      phone: "+52 656 555 0189",
      stage: "propuesta enviada",
      estimatedValue: 145000,
      closeProbability: 72,
      nextStep: "Ajustar alcance de tablero logistico",
      source: "LinkedIn",
      lastInteraction: "2026-06-28",
      recommendedPackage: "Proyecto Integral",
      intake: {
        yearsOperating: 8,
        howFoundUs: "LinkedIn",
        mainProblem: "Retrasos constantes y falta de tablero operativo.",
        expectedResult: "Reducir retrasos y tener control diario por ruta.",
        previousConsulting: "sí",
        previousExperienceNotes: "Funcionó el diagnóstico, pero no hubo implementación.",
        budgetAvailable: "evaluando",
        willingToParticipate: "sí",
        internalFlag: "amarillo",
      },
    },
    {
      id: "lead_derma",
      company: "Clinica DermaNova",
      contactName: "Paola Rios",
      email: "paola@dermanova.mx",
      phone: "+52 656 770 9011",
      stage: "negociacion",
      estimatedValue: 118000,
      closeProbability: 81,
      nextStep: "Reunion con direccion financiera",
      source: "Evento",
      lastInteraction: "2026-06-30",
      recommendedPackage: "Diagnóstico + Implementación",
      intake: {
        yearsOperating: 3,
        howFoundUs: "Evento",
        mainProblem: "No saben qué campañas generan pacientes ni recompra.",
        expectedResult: "Mejorar conversión de valoraciones y ordenar postventa.",
        previousConsulting: "no",
        budgetAvailable: "definido",
        willingToParticipate: "sí",
        internalFlag: "verde",
      },
    },
    {
      id: "lead_fundicion",
      company: "Fundicion Norte",
      contactName: "Ramon Trejo",
      email: "rtrejo@fundicionnorte.mx",
      phone: "+52 656 404 3000",
      stage: "formulario 1 enviado",
      estimatedValue: 210000,
      closeProbability: 38,
      nextStep: "Enviar checklist de procesos",
      source: "Web",
      lastInteraction: "2026-06-27",
      recommendedPackage: "Diagnóstico Express + Recomendaciones",
      intake: {
        yearsOperating: 11,
        howFoundUs: "Búsqueda en internet",
        mainProblem: "Retrabajos y procesos no documentados.",
        expectedResult: "Identificar causa raíz y priorizar orden operativo.",
        previousConsulting: "sí",
        previousExperienceNotes: "No hubo claridad de responsables.",
        budgetAvailable: "evaluando",
        willingToParticipate: "prefiere delegar",
        internalFlag: "amarillo",
      },
    },
  ],
  clients: [
    {
      id: "client_optica",
      name: "Optica Vista Clara",
      industry: "Optica y retail salud",
      size: "18 colaboradores",
      health: "amarillo",
      accountOwner: "Mateo Ruiz",
      mainPain: "Seguimiento inconsistente a prospectos y baja visibilidad de inventario.",
      services: ["Diagnostico operativo", "Implementacion CRM", "KPIs comerciales"],
      revenueEstimate: 92000,
      since: "2026-04-12",
      expedienteIds: ["diag_optica"],
    },
    {
      id: "client_logistica",
      name: "Ruta Frontera Logistics",
      industry: "Logistica y transporte",
      size: "64 colaboradores",
      health: "rojo",
      accountOwner: "Laura Cardenas",
      mainPain: "Retrasos recurrentes, rutas sin medicion y comunicacion reactiva con clientes.",
      services: ["Rediseño de procesos", "Tablero operativo", "Seguimiento postventa"],
      revenueEstimate: 185000,
      since: "2026-03-03",
      expedienteIds: [],
    },
    {
      id: "client_clinica",
      name: "Aura Clinic",
      industry: "Clinica estetica",
      size: "27 colaboradores",
      health: "verde",
      accountOwner: "Sofia Vega",
      mainPain: "No existe lectura clara de conversion por tratamiento ni recompra.",
      services: ["Mejora de ventas", "Campaña comercial", "Automatizacion administrativa"],
      revenueEstimate: 126000,
      since: "2026-05-08",
      expedienteIds: [],
    },
    {
      id: "client_industrial",
      name: "Industrias Calderon",
      industry: "Manufactura industrial",
      size: "120 colaboradores",
      health: "amarillo",
      accountOwner: "Laura Cardenas",
      mainPain: "Procesos no documentados, retrabajos y costos indirectos sin control.",
      services: ["Estandarizacion de procesos", "Analisis financiero basico"],
      revenueEstimate: 240000,
      since: "2026-02-18",
      expedienteIds: [],
    },
  ],
  contacts: [
    {
      id: "ct_opt_1",
      clientId: "client_optica",
      name: "Mariana Leon",
      role: "Directora general",
      email: "mariana@vistaclara.mx",
      phone: "+52 656 111 2930",
    },
    {
      id: "ct_log_1",
      clientId: "client_logistica",
      name: "Jorge Quintana",
      role: "Director de operaciones",
      email: "jorge@rutafrontera.mx",
      phone: "+52 656 220 1301",
    },
    {
      id: "ct_cli_1",
      clientId: "client_clinica",
      name: "Ana Portillo",
      role: "Gerente comercial",
      email: "ana@auraclinic.mx",
      phone: "+52 656 340 9900",
    },
    {
      id: "ct_ind_1",
      clientId: "client_industrial",
      name: "Ricardo Calderon",
      role: "Director industrial",
      email: "ricardo@industriascalderon.mx",
      phone: "+52 656 721 2000",
    },
  ],
  interactions: [
    {
      id: "int_1",
      clientId: "client_logistica",
      type: "reunion",
      title: "Revision de retrasos por ruta",
      detail: "Se detectaron cuellos de botella en confirmacion de carga y evidencia de entrega.",
      date: "2026-06-26",
    },
    {
      id: "int_2",
      clientId: "client_optica",
      type: "llamada",
      title: "Seguimiento CRM",
      detail: "El equipo necesita campos obligatorios para origen, graduacion y proxima cita.",
      date: "2026-06-25",
    },
    {
      id: "int_3",
      leadId: "lead_derma",
      type: "nota",
      title: "Objecion de presupuesto",
      detail: "Solicitaron dividir la implementacion en dos fases mensuales.",
      date: "2026-06-30",
    },
  ],
  intakeForms: [
    {
      id: "intake_optica",
      clientId: "client_optica",
      company: "Optica Vista Clara",
      industry: "Optica",
      size: "18 colaboradores",
      currentProblems: "Inventario desordenado, cotizaciones sin seguimiento y poca visibilidad por sucursal.",
      objectives: "Aumentar conversion de consultas, reducir faltantes y controlar recompra.",
      criticalProcesses: "Ventas, agenda de examenes, inventario, postventa.",
      tools: "Excel, WhatsApp Business y punto de venta local.",
      sales: "No se mide conversion por vendedor.",
      operations: "Reposicion reactiva de armazones y micas.",
      finance: "Margen por producto calculado de forma manual.",
      marketing: "Campañas esporadicas en Meta.",
      customerService: "Recordatorios manuales de citas.",
      urgency: "alta",
      budget: "$70,000 - $100,000",
      priorities: "CRM, inventario, indicadores semanales.",
      createdAt: "2026-04-13",
    },
  ],
  diagnoses: [
    {
      id: "diag_optica",
      clientId: "client_optica",
      intakeId: "intake_optica",
      company: "Optica Vista Clara",
      summary:
        "La operacion comercial depende de seguimiento manual y no existe un tablero comun para ventas, inventario y recompra.",
      detectedProblems: [
        "Pipeline comercial sin etapas estandarizadas",
        "Inventario con reposicion reactiva",
        "Indicadores de conversion y margen no confiables",
      ],
      opportunities: [
        "Implementar CRM ligero con reglas de proxima accion",
        "Crear tablero semanal de ventas, inventario y recompra",
        "Estandarizar recordatorios postconsulta",
      ],
      suggestedKpis: ["Conversion consulta-venta", "Dias de inventario", "Recompra a 90 dias"],
      possibleProjects: ["Implementacion CRM", "Control de inventarios", "Seguimiento postventa"],
      interventionPriority: "alta",
      createdAt: "2026-04-14",
      approach: "comercial",
      recommendedPackage: "Diagnóstico + Implementación",
    },
  ],
  recipes: [
    {
      id: "recipe_diagnostico",
      name: "Diagnostico operativo",
      problem: "La direccion no tiene claridad sobre causas raiz ni prioridades.",
      symptoms: ["Decisiones por intuicion", "Retrabajo frecuente", "Indicadores dispersos"],
      steps: ["Mapear procesos", "Entrevistar responsables", "Medir cuellos de botella", "Priorizar intervenciones"],
      kpis: ["Tiempo de ciclo", "Retrabajo", "Cumplimiento semanal"],
      deliverables: ["Mapa de procesos", "Matriz de hallazgos", "Roadmap 30-60-90"],
      durationWeeks: 2,
      difficulty: "media",
      suggestedTasks: ["Agenda de entrevistas", "Levantamiento de datos", "Presentacion ejecutiva"],
      templates: ["Checklist operativo", "Matriz impacto/esfuerzo"],
    },
    {
      id: "recipe_crm",
      name: "Implementacion de CRM",
      problem: "Prospectos y clientes se pierden por seguimiento informal.",
      symptoms: ["No hay proximas acciones", "WhatsApp como unica fuente", "No se mide conversion"],
      steps: ["Definir pipeline", "Diseñar campos", "Migrar cartera", "Capacitar equipo", "Medir adopcion"],
      kpis: ["Conversion por etapa", "Tiempo de respuesta", "Actividad por ejecutivo"],
      deliverables: ["Pipeline configurado", "Manual de uso", "Tablero comercial"],
      durationWeeks: 4,
      difficulty: "media",
      suggestedTasks: ["Taller de pipeline", "Carga inicial", "Prueba piloto"],
      templates: ["Campos CRM", "Script de seguimiento"],
    },
    {
      id: "recipe_inventarios",
      name: "Control de inventarios",
      problem: "Faltantes, sobreinventario y baja visibilidad de rotacion.",
      symptoms: ["Compras urgentes", "Diferencias fisicas", "Productos detenidos"],
      steps: ["Clasificar inventario", "Definir minimos", "Crear conteos ciclicos", "Tablero de rotacion"],
      kpis: ["Exactitud de inventario", "Dias de inventario", "Rotacion"],
      deliverables: ["Catalogo depurado", "Politica de reposicion", "Tablero de inventario"],
      durationWeeks: 5,
      difficulty: "alta",
      suggestedTasks: ["Conteo muestra", "Limpieza de catalogo", "Reglas de compra"],
      templates: ["ABC inventario", "Formato conteo ciclico"],
    },
    {
      id: "recipe_ventas",
      name: "Mejora de ventas",
      problem: "El equipo vende sin proceso ni medicion consistente.",
      symptoms: ["Baja conversion", "Seguimiento irregular", "Metas poco claras"],
      steps: ["Auditar embudo", "Diseñar rutina comercial", "Crear tablero", "Coaching semanal"],
      kpis: ["Leads atendidos", "Conversion", "Ticket promedio"],
      deliverables: ["Rutina comercial", "Guia de seguimiento", "Dashboard de ventas"],
      durationWeeks: 6,
      difficulty: "media",
      suggestedTasks: ["Revision de cartera", "Definir cadencias", "Sesiones de roleplay"],
      templates: ["Guion llamada", "Agenda semanal ventas"],
    },
  ],
  projects: [
    {
      id: "proj_opt_crm",
      clientId: "client_optica",
      name: "CRM y seguimiento comercial",
      objective: "Aumentar conversion y visibilidad de oportunidades por sucursal.",
      scope: "Pipeline, campos, tablero, capacitacion y rutina semanal.",
      owner: "Mateo Ruiz",
      startsAt: "2026-06-10",
      endsAt: "2026-07-22",
      status: "en progreso",
      priority: "alta",
      budget: 88000,
      progress: 58,
      risks: ["Adopcion irregular por vendedores", "Datos historicos incompletos"],
      kpiIds: ["kpi_opt_conversion"],
      packageType: "Diagnóstico + Implementación",
    },
    {
      id: "proj_log_ops",
      clientId: "client_logistica",
      name: "Control tower logistico",
      objective: "Reducir retrasos y crear seguimiento diario por ruta.",
      scope: "Mapa de flujo, tablero de rutas, acuerdos de escalamiento y minuta operativa.",
      owner: "Laura Cardenas",
      startsAt: "2026-05-20",
      endsAt: "2026-07-31",
      status: "en progreso",
      priority: "critica",
      budget: 165000,
      progress: 42,
      risks: ["Datos de operadores llegan tarde", "Clientes clave exigen evidencias diarias"],
      kpiIds: ["kpi_log_otd"],
      packageType: "Proyecto Integral",
    },
    {
      id: "proj_cli_sales",
      clientId: "client_clinica",
      name: "Motor comercial de tratamientos",
      objective: "Incrementar conversion de valoraciones y recompra.",
      scope: "Segmentacion, campanas, scripts, tablero comercial y seguimiento postventa.",
      owner: "Sofia Vega",
      startsAt: "2026-06-01",
      endsAt: "2026-07-12",
      status: "en revision",
      priority: "media",
      budget: 98000,
      progress: 86,
      risks: ["Aprobacion lenta de contenidos"],
      kpiIds: ["kpi_cli_conversion"],
      packageType: "Sprint de Mejora",
    },
  ],
  phases: [
    { id: "ph1", projectId: "proj_opt_crm", name: "Diseno pipeline", startsAt: "2026-06-10", endsAt: "2026-06-21", progress: 100 },
    { id: "ph2", projectId: "proj_opt_crm", name: "Configuracion y carga", startsAt: "2026-06-22", endsAt: "2026-07-08", progress: 60 },
    { id: "ph3", projectId: "proj_opt_crm", name: "Capacitacion y adopcion", startsAt: "2026-07-09", endsAt: "2026-07-22", progress: 15 },
    { id: "ph4", projectId: "proj_log_ops", name: "Levantamiento operativo", startsAt: "2026-05-20", endsAt: "2026-06-05", progress: 100 },
    { id: "ph5", projectId: "proj_log_ops", name: "Tablero de rutas", startsAt: "2026-06-06", endsAt: "2026-07-03", progress: 55 },
    { id: "ph6", projectId: "proj_log_ops", name: "Ritual de seguimiento", startsAt: "2026-07-04", endsAt: "2026-07-31", progress: 10 },
  ],
  tasks: [
    {
      id: "task_1",
      title: "Configurar etapas del pipeline optica",
      description: "Nuevo lead, examen agendado, cotizacion, compra, recompra.",
      clientId: "client_optica",
      projectId: "proj_opt_crm",
      owner: "Mateo Ruiz",
      dueDate: "2026-07-03",
      priority: "alta",
      status: "en proceso",
      checklist: [
        { label: "Validar etapas con direccion", done: true },
        { label: "Crear campos obligatorios", done: true },
        { label: "Probar captura con vendedor", done: false },
      ],
      comments: ["Pendiente confirmar campos de graduacion."],
      relation: "kpi_opt_conversion",
    },
    {
      id: "task_2",
      title: "Tablero diario de entregas atrasadas",
      description: "Vista por ruta, operador, cliente y causa raiz.",
      clientId: "client_logistica",
      projectId: "proj_log_ops",
      owner: "Laura Cardenas",
      dueDate: "2026-06-28",
      priority: "critica",
      status: "bloqueada",
      checklist: [
        { label: "Definir causa raiz", done: true },
        { label: "Conectar fuente de despacho", done: false },
      ],
      comments: ["Operacion aun no entrega archivo diario limpio."],
      relation: "kpi_log_otd",
    },
    {
      id: "task_3",
      title: "Guion de seguimiento postvaloracion",
      description: "Script y cadencia para valoraciones sin cierre.",
      clientId: "client_clinica",
      projectId: "proj_cli_sales",
      owner: "Sofia Vega",
      dueDate: "2026-07-05",
      priority: "media",
      status: "en revision",
      checklist: [
        { label: "Version WhatsApp", done: true },
        { label: "Version llamada", done: true },
      ],
      comments: ["Cliente revisa tono del mensaje."],
      relation: "kpi_cli_conversion",
    },
    {
      id: "task_4",
      title: "Mapear proceso de orden de produccion",
      description: "Documentar responsables, entradas, salidas y puntos de retrabajo.",
      clientId: "client_industrial",
      owner: "Laura Cardenas",
      dueDate: "2026-07-08",
      priority: "alta",
      status: "pendiente",
      checklist: [{ label: "Agendar entrevistas", done: false }],
      comments: [],
      relation: "entregable mapa de procesos",
    },
  ],
  kpis: [
    {
      id: "kpi_opt_conversion",
      clientId: "client_optica",
      projectId: "proj_opt_crm",
      name: "Conversion consulta-venta",
      description: "Porcentaje de examenes visuales que terminan en compra.",
      formula: "Ventas / consultas",
      currentValue: 42,
      target: 58,
      unit: "%",
      frequency: "Semanal",
      owner: "Mateo Ruiz",
      source: "CRM",
      status: "alerta",
    },
    {
      id: "kpi_log_otd",
      clientId: "client_logistica",
      projectId: "proj_log_ops",
      name: "Entregas a tiempo",
      description: "Porcentaje de viajes entregados dentro de ventana prometida.",
      formula: "Entregas a tiempo / entregas totales",
      currentValue: 71,
      target: 90,
      unit: "%",
      frequency: "Diaria",
      owner: "Laura Cardenas",
      source: "Despacho",
      status: "critico",
    },
    {
      id: "kpi_cli_conversion",
      clientId: "client_clinica",
      projectId: "proj_cli_sales",
      name: "Conversion valoracion-tratamiento",
      description: "Pacientes que contratan despues de una valoracion.",
      formula: "Tratamientos vendidos / valoraciones",
      currentValue: 63,
      target: 68,
      unit: "%",
      frequency: "Semanal",
      owner: "Sofia Vega",
      source: "Agenda + ventas",
      status: "bien",
    },
  ],
  kpiMeasurements: [
    { id: "m1", kpiId: "kpi_opt_conversion", date: "2026-06-01", value: 33 },
    { id: "m2", kpiId: "kpi_opt_conversion", date: "2026-06-08", value: 36 },
    { id: "m3", kpiId: "kpi_opt_conversion", date: "2026-06-15", value: 39 },
    { id: "m4", kpiId: "kpi_opt_conversion", date: "2026-06-22", value: 42 },
    { id: "m5", kpiId: "kpi_log_otd", date: "2026-06-01", value: 68 },
    { id: "m6", kpiId: "kpi_log_otd", date: "2026-06-08", value: 70 },
    { id: "m7", kpiId: "kpi_log_otd", date: "2026-06-15", value: 69 },
    { id: "m8", kpiId: "kpi_log_otd", date: "2026-06-22", value: 71 },
    { id: "m9", kpiId: "kpi_cli_conversion", date: "2026-06-01", value: 55 },
    { id: "m10", kpiId: "kpi_cli_conversion", date: "2026-06-08", value: 59 },
    { id: "m11", kpiId: "kpi_cli_conversion", date: "2026-06-15", value: 61 },
    { id: "m12", kpiId: "kpi_cli_conversion", date: "2026-06-22", value: 63 },
  ],
  meetings: [
    {
      id: "meet_1",
      clientId: "client_logistica",
      projectId: "proj_log_ops",
      title: "Ritual operativo semanal",
      date: "2026-07-02",
      minutes: "Se revisaron rutas criticas, evidencia de entrega y causas por retraso.",
      agreements: ["Operacion enviara archivo diario antes de 9:00", "LC entregara tablero v1"],
      owners: ["Jorge Quintana", "Laura Cardenas"],
      nextMeeting: "2026-07-09",
      decisions: ["Usar entregas a tiempo como KPI rector"],
      risks: ["Baja disciplina de captura por operadores"],
    },
    {
      id: "meet_2",
      clientId: "client_optica",
      projectId: "proj_opt_crm",
      title: "Revision CRM piloto",
      date: "2026-07-04",
      minutes: "Se revisaron campos obligatorios y rutina de seguimiento.",
      agreements: ["Vendedores probaran captura por 5 dias", "Direccion validara reporte semanal"],
      owners: ["Mariana Leon", "Mateo Ruiz"],
      nextMeeting: "2026-07-11",
      decisions: ["Activar campo de proxima cita como obligatorio"],
      risks: ["Resistencia del equipo de sucursal 2"],
    },
  ],
  deliverables: [
    {
      id: "del_1",
      clientId: "client_optica",
      projectId: "proj_opt_crm",
      name: "Tablero comercial v1",
      description: "Pipeline, conversion por etapa y proximas acciones.",
      dueDate: "2026-07-08",
      status: "en revision",
      owner: "Mateo Ruiz",
      link: "https://example.com/tablero-comercial",
      comments: "Falta ajustar filtro por sucursal.",
      approvedByClient: false,
    },
    {
      id: "del_2",
      clientId: "client_logistica",
      projectId: "proj_log_ops",
      name: "Mapa de flujo despacho-entrega",
      description: "Mapa operativo con causas de retraso y responsables.",
      dueDate: "2026-07-01",
      status: "pendiente",
      owner: "Laura Cardenas",
      link: "",
      comments: "Pendiente validar con operaciones.",
      approvedByClient: false,
    },
    {
      id: "del_3",
      clientId: "client_clinica",
      projectId: "proj_cli_sales",
      name: "Playbook comercial",
      description: "Cadencias, guiones y politicas de seguimiento.",
      dueDate: "2026-07-06",
      status: "aprobado",
      owner: "Sofia Vega",
      link: "https://example.com/playbook",
      comments: "Aprobado por gerencia comercial.",
      approvedByClient: true,
    },
  ],
  reports: [
    {
      id: "rep_1",
      type: "ejecutivo cliente",
      title: "Executive brief - Ruta Frontera Logistics",
      period: "Junio 2026",
      status: "listo",
      summary: "Riesgo alto por entregas tardias; tablero operativo en construccion y ritual semanal iniciado.",
      generatedAt: "2026-06-30",
    },
    {
      id: "rep_2",
      type: "crm comercial",
      title: "Pipeline comercial LC Consulting",
      period: "Semana 27",
      status: "listo",
      summary: "Valor ponderado en pipeline: $289k MXN. Tres oportunidades en propuesta/negociacion.",
      generatedAt: "2026-06-30",
    },
    {
      id: "rep_3",
      type: "tareas atrasadas",
      title: "Tareas atrasadas y bloqueadas",
      period: "01 julio 2026",
      status: "borrador",
      summary: "Una tarea critica bloqueada por fuente de datos operativa.",
      generatedAt: "2026-07-01",
    },
  ],
  clientHistory: [
    {
      id: "hist_1",
      clientId: "client_optica",
      date: "2026-04-14",
      actor: "Mateo Ruiz",
      title: "Expediente inicial generado",
      detail: "Se registró diagnóstico comercial y prioridad alta para CRM e inventario.",
    },
    {
      id: "hist_2",
      clientId: "client_logistica",
      date: "2026-06-26",
      actor: "Laura Cárdenas",
      title: "Riesgo operativo actualizado",
      detail: "Se marcó salud roja por entregas tardías y falta de evidencia diaria.",
    },
  ],
  consultants: [
    {
      id: "consultant_laura",
      name: "Laura Cárdenas",
      role: "Directora estratégica",
      email: "laura@lcconsulting.mx",
      phone: "+52 656 100 0001",
      specialties: ["Operaciones", "KPIs", "Transformación"],
      status: "ocupado",
      capacity: 85,
      projectIds: ["proj_log_ops"],
    },
    {
      id: "consultant_mateo",
      name: "Mateo Ruiz",
      role: "Consultor operativo",
      email: "mateo@lcconsulting.mx",
      phone: "+52 656 100 0002",
      specialties: ["CRM", "Ventas", "Procesos"],
      status: "ocupado",
      capacity: 70,
      projectIds: ["proj_opt_crm"],
    },
    {
      id: "consultant_sofia",
      name: "Sofía Vega",
      role: "Consultora comercial",
      email: "sofia@lcconsulting.mx",
      phone: "+52 656 100 0003",
      specialties: ["Marketing", "Postventa", "Coaching"],
      status: "disponible",
      capacity: 45,
      projectIds: ["proj_cli_sales"],
    },
  ],
  packages: consultingPackages.map((item) => ({ ...item })),
};

export function generateDiagnosis(input: IntakeForm): Diagnosis {
  const text = [
    input.currentProblems,
    input.objectives,
    input.criticalProcesses,
    input.sales,
    input.operations,
    input.finance,
    input.marketing,
    input.customerService,
    input.priorities,
  ]
    .join(" ")
    .toLowerCase();

  const detectedProblems = [
    text.includes("inventario") ? "Control de inventarios reactivo o poco confiable" : "Procesos criticos sin medicion consistente",
    text.includes("venta") || text.includes("crm") ? "Seguimiento comercial sin cadencia estandar" : "Falta de tablero ejecutivo para priorizar decisiones",
    text.includes("finan") || text.includes("margen") ? "Visibilidad financiera insuficiente por servicio o producto" : "Responsables y acuerdos operativos dispersos",
  ];

  const opportunities = [
    "Crear un tablero semanal con responsables, fechas y semaforos",
    text.includes("crm") || text.includes("venta")
      ? "Implementar pipeline comercial con proximas acciones obligatorias"
      : "Documentar proceso rector y puntos de control",
    text.includes("inventario")
      ? "Definir minimos, conteos ciclicos y reglas de reposicion"
      : "Estandarizar reuniones de seguimiento con acuerdos convertidos en tareas",
  ];

  const suggestedKpis = [
    text.includes("venta") ? "Conversion por etapa" : "Cumplimiento semanal",
    text.includes("inventario") ? "Exactitud de inventario" : "Tiempo de ciclo",
    text.includes("cliente") ? "Tiempo de respuesta al cliente" : "Avance de proyecto",
  ];

  const possibleProjects = [
    text.includes("crm") || text.includes("venta") ? "Implementacion de CRM" : "Diagnostico operativo",
    text.includes("inventario") ? "Control de inventarios" : "Rediseño de procesos",
    text.includes("automat") ? "Automatizacion administrativa" : "Tablero de KPIs",
  ];

  const interventionPriority: Priority =
    input.urgency === "alta" ? "alta" : input.urgency === "media" ? "media" : "baja";

  return {
    id: uid("diag"),
    clientId: input.clientId,
    intakeId: input.id,
    company: input.company,
    summary: `${input.company} requiere ordenar ${input.criticalProcesses.toLowerCase()} y convertir los problemas actuales en proyectos medibles con responsables claros.`,
    detectedProblems,
    opportunities,
    suggestedKpis,
    possibleProjects,
    interventionPriority,
    createdAt: new Date().toISOString().slice(0, 10),
  };
}

export function kpiTone(status: KpiStatus) {
  if (status === "bien") return "text-emerald-700 bg-emerald-50 border-emerald-200";
  if (status === "alerta") return "text-amber-700 bg-amber-50 border-amber-200";
  return "text-rose-700 bg-rose-50 border-rose-200";
}
